version: '3'

services:
  shopkartoncontainers:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  catalogapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  basketapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  orderingapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
networks:
  default:
    external:
      name: nat



